name = "scms"
main = "./backend/auth-worker.js"
compatibility_date = "2026-03-16"
workers_dev = true
routes = [
  { pattern = "scms.seastar.work/*", zone_name = "seastar.work" }
]

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
ADMIN_PASSWORD = ""
NAVER_CLIENT_ID = "Sc7hFrtTJvFG2vfxWzM"
NAVER_CLIENT_SECRET = "LZCk6JFWxy"
